{
 "title": "Rabbit MQ",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Consumers for queue",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_queue_consumers{queue=\"FIRST-QUEUE-ADVANCED\"}",
     "legendFormat": "Consumers for FIRST-QUEUE-ADVANCED"
    }
   ]
  },
  {
   "title": "DLQ Elements",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rabbitmq_queue_messages{queue=\"DLQ-QUEUE\"}",
     "legendFormat": "Dlq elements"
    }
   ]
  },
  {
   "title": "Elements at queue",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_queue_messages{queue=\"FIRST-QUEUE-ADVANCED\"}"
    }
   ]
  }
 ]
}