{
 "title": "Aula",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Usuários ativos",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "aula_usuarios_logados_total" }
   ]
  },
  {
   "title": "Request/segundo",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Requests" }
   ],
   "targets": [
    {
     "expr": "sum(rate(aula_requests_total[1m]))",
     "legendFormat": "API"
    }
   ]
  },
  {
   "title": "Requisições no momento",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(aula_requests_total[$__range]))"
    }
   ]
  },
  { "title": "Alert list", "type": "alertlist", "gridPos": { "h": 8, "w": 5, "x": 7, "y": 9 } },
  {
   "title": "Taxa de erros",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "percentunit", "label": "% erros" }
   ],
   "targets": [
    {
     "expr": "sum(rate(aula_requests_total{statusCode=\"500\"}[1m])) / sum(rate(aula_requests_total[1m]))",
     "legendFormat": "http 500"
    }
   ]
  },
  {
   "title": "Percentil",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(aula_request_duration_seconds_bucket[1m]))by (le))",
     "legendFormat": "90%"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(aula_request_duration_seconds_bucket[1m]))by (le))",
     "legendFormat": "95%"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(aula_request_duration_seconds_bucket[1m]))by (le))",
     "legendFormat": "99%"
    }
   ]
  }
 ]
}